unit TestUValorTotal;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, UValorTotal;

type
  // Test methods for class TValorTotal

  TestTValorTotal = class(TTestCase)
  strict private
    FValorTotal: TValorTotal;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestRetornarValorTotal;
  end;

implementation

procedure TestTValorTotal.SetUp;
begin
  FValorTotal := TValorTotal.Create;
end;

procedure TestTValorTotal.TearDown;
begin
  FValorTotal.Free;
  FValorTotal := nil;
end;

procedure TestTValorTotal.TestRetornarValorTotal;
var
  ReturnValue: Double;
begin
  FValorTotal.Quantidade := 10;
  FValorTotal.PrecoUnitario := 10;

  ReturnValue := FValorTotal.RetornarValorTotal;
  CheckEquals(100, ReturnValue, 'Erro')
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTValorTotal.Suite);
end.

